### ISSUE TITLE
Redirect isn't working for fully qualified urls

### ISSUE THREAD

**Issue by vvilhonen** [reid/pact#1]
When the server http://example.com sends a http 302 with Location: http://google.com pact sends a request to http://example.com/http://google.com.

**Comment by reid** [comment]
Hi there!

Good find. I'm now checking for this in Pact in reid/pact@1ea43901166302155dd667a4e300d2fd258df16a.

Since Pact helps test local HTTP servers, I'm no longer handling 302 redirects with absolute URLs. Only relative URLs will be resolved internally. For absolute URLs, you should get back a `topic.status` 302 with the absolute URL in `topic.headers["location"]`.

I've updated inline documentation to reflect this. I've also added a test suite. Type `make test` to invoke (requires [Vows](http://vowsjs.org/)).

**Comment by vvilhonen** [comment]
Great, thank you!
